package Tests;

import Domain.LoginException;
import org.junit.Test;

public class SessionControllerTest {

    @Test
    public void testSessionController() throws LoginException {
        /*
        Session omer = new Session();
        UserManager um = new UserManager();
        SessionController sc = new SessionController(omer, um);

        assertFalse(sc.logout());
        assertTrue(sc.loginPrecondition());
        // enter wrong username / password
        assertThrows(LoginException.class, () -> sc.login("Thomas", "1234"));
        assertThrows(LoginException.class, () -> sc.login("WardGr", "toilet573"));
        assertThrows(LoginException.class, () -> sc.login("OlavBl", "minecraft123"));
        assertTrue(sc.loginPrecondition());

        sc.login("WardGr", "minecraft123");
        assertFalse(sc.loginPrecondition());

        //login while already logged in
        assertThrows(LoginException.class, () -> sc.login("OlavBl", "toilet573"));
        assertThrows(LoginException.class, () -> sc.login("WardGr", "minecraft123"));
        assertFalse(sc.loginPrecondition());

        assertTrue(sc.logout());
        assertTrue(sc.loginPrecondition());
        assertFalse(sc.logout());

        */

    }
}
